apiVersion: v1
kind: Service
metadata:
  name: dev-admin-member
spec:
  type: NodePort
  selector:
    app: dev-admin-member
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-admin-member
  namespace: default
  labels:
    app: dev-admin-member
spec:
  # 테스트를 위해 우선 1개로 지정
  replicas: 1
  selector:
    matchLabels:
      app: dev-admin-member
      
#  strategy:
#    rollingUpdate:
#      maxSurge: 1
#      maxUnavailable: 1
#    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dev-admin-member
    spec:
      containers:
        - name: dev-admin-member
          image: AWS_ECR_URI
          ports:
            - containerPort: 9080
          imagePullPolicy: Always
#          command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
#          resources:
#            requests:
#              cpu: "256m"
#              memory: "512Mi"
#            limits:
#              cpu: "256m"
#              memory: "512Mi"