apiVersion: v1
kind: Service
metadata:
  name: donots-admin
spec:
  type: NodePort
  selector:
    app: donots-admin
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: donots-admin
  namespace: default
  labels:
    app: donots-admin
spec:
  # 테스트를 위해 우선 1개로 지정
  replicas: 1
  selector:
    matchLabels:
      app: donots-admin
      
#  strategy:
#    rollingUpdate:
#      maxSurge: 1
#      maxUnavailable: 1
#    type: RollingUpdate
  template:
    metadata:
      labels:
        app: donots-admin
    spec:
      containers:
        - name: donots-admin
          image: AWS_ECR_URI
          ports:
            - containerPort: 9090
          imagePullPolicy: Always
#          command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
#          resources:
#            requests:
#              cpu: "256m"
#              memory: "512Mi"
#            limits:
#              cpu: "256m"
#              memory: "512Mi" 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: donots-admin-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: eks-admin-group
    alb.ingress.kubernetes.io/group.order: '1'
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: donots-admin
              port:
                number: 9090