server:
  servlet:
    session:
      timeout: 1800
  port : 9090
spring :
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: jdbc:postgresql://localhost:5432/donots_account
      username: postgres
      password: kyobo11!
      driver-class-name: org.postgresql.Driver
      data-source-properties :
        rewriteBatchedStatements: true
  session:
     store-type: redis
#     redis:
#       namespace: spring:admin
  redis:
     host: localhost
     port: 6379
     database: 0
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: 'update'
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    properties:
      hibernate:
      show_sql: true
      format_sql: true
      use_sql_comments: true
logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
    rolling-file-name: "/logs/abc.%d{yyyy-MM-dd}.%i"
  file:
    name: /logs/abc.log
    max-history: 30
  level:
    org:
      springframework: INFO

