server:
  port: 9080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://account-db.crfubebnxuuv.ap-northeast-2.rds.amazonaws.com:5432/donots_account
    username: postgres
    password: kyobo11!
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: jdbc:postgresql://account-db.crfubebnxuuv.ap-northeast-2.rds.amazonaws.com:5432/donots_account
      username: postgres
      password: kyobo11!
      driver-class-name: org.postgresql.Driver
      data-source-properties:
        rewriteBatchedStatements: true
  session:
    store-type: redis
#  redis:
#    host: donot-redis-ro.mpt7r0.ng.0001.apn2.cache.amazonaws.com
##    host: localhost
#    port: 6379
#    database: 0
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: 'update'
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    properties:
      hibernate:
      show_sql: true
      format_sql: true
      use_sql_comments: true
logging:
  level:
    root: info